[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "numpy>=2.3.2",
    "open-spiel>=1.6",
    "pandas>=2.3.1",
    "pydantic>=2.11.7",
    "pytest>=8.4.1",
    "trafilatura>=2.0.0",
    "uvicorn[standard]>=0.35.0",
    "websockets>=15.0.1",
]
